# K-Nearest Neighbors

En este caso vamos a estar usando K-NN para clasificacion por lo cual la salida va a ser calculada como la moda en los K datos mas cercanos.

### importamos las librerias necesarias

In [26]:
import pandas as pd
import pandas_profiling as pdp
import numpy as np

In [18]:
data = pd.read_csv('breast-cancer.csv')

In [19]:
data.head()

,id,Clump_Thickness,Uniformity_of_Cell_Size,Uniformity_of_Cell_Shape,Marginal_Adhesion,Single_Epithelial_Cell_Size,Bare_Nuclei,Bland_Chromatin,Normal_Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2

### Missing Values

Como ya vimos en la seccion de [missing values](./) Bare Nuclei tiene missing values por lo cual los eliminamos.

In [20]:
data = data.drop(['id'], axis=1)

data = data[data.Bare_Nuclei!='?']

data.Bare_Nuclei = data.Bare_Nuclei.apply(lambda x: int(x))

In [21]:
data.describe()

,Clump_Thickness,Uniformity_of_Cell_Size,Uniformity_of_Cell_Shape,Marginal_Adhesion,Single_Epithelial_Cell_Size,Bland_Chromatin,Normal_Nucleoli,Mitoses,Class
count,683.000000,683.000000,683.000000,683.000000,683.000000,683.000000,683.000000,683.000000,683.000000
mean,4.442167,3.150805,3.215227,2.830161,3.234261,3.445095,2.869693,1.603221,2.699854
std,2.820761,3.065145,2.988581,2.864562,2.223085,2.449697,3.052666,1.732674,0.954592
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
25%,2.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000,2.000000
50%,4.000000,1.000000,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000,2.000000
75%,6.000000,5.000000,5.000000,4.000000,4.000000,5.000000,4.000000,1.000000,4.000000
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,4.000000

In [212]:
class KNN:
    def __init__(self):
        pass

    def train(self, X, y):
        self.X_train = X
        self.y_train = y
       
    def predict(self, X, k=1):
        """
        Calculamos la distancia L2 entre los datos de test y validacion, devolviendo la moda en k
        """
        distances = []
        predictions = []
        for test_sample in X:
            for index, train_sample in enumerate(self.X_train):
                distances.append(np.linalg.norm(test_sample-train_sample))
            k_closest = np.take(self.y_train, np.argsort(distances)[:k])
            counts = np.bincount(k_closest)
            y_pred = np.argmax(counts)
            predictions.append(y_pred)
            distances = []
        return predictions

In [211]:
from sklearn.model_selection import train_test_split

# Creamos una instancia de nuestro clasificador KNN
knn = KNN()
# Separamos la label de los datos
y = data.Class
X = data.drop(['Class'], axis=1)
# Hacemos un split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)
# Entrenamos nuestro modelo
knn.train(X_train.values, y_train.values)
# Hacemos las predicciones
predictions = knn.predict(X_test.values, 5)
# Calculamos el error
differences = abs(predictions - y_test.values)
unique, predictions = np.unique(differences, return_counts=True)
correct_predictions = predictions[0]
wrong_predictions = predictions[1]
# Calculamos la accuracy
accuracy = correct_predictions/(correct_predictions+wrong_predictions)

print('Accuracy: {0}'.format(accuracy))

Accuracy: 0.9609756097560975

Podemos ver que se llega a una accuracy relativamente alta.